#!/bin/bash

export CM_GIT_BRANCH="mlperf-inference-results-scc24"
export CM_GIT_CHECKOUT_PATH="/home/cmuser/CM/repos/local/cache/874f8b979b994f9e/repo"
export CM_GIT_REPO_CHECKOUT="mlperf-inference-results-scc24"
export CM_GIT_REPO_CHECKOUT_FOLDER="repo"
export CM_GIT_REPO_CHECKOUT_PATH="/home/cmuser/CM/repos/local/cache/874f8b979b994f9e/repo"
export CM_GIT_REPO_CURRENT_HASH="26277a4039636d653c233ec6fd299168bbca9511"
export CM_GIT_REPO_DEPTH="--depth 5"
export CM_GIT_REPO_NAME="cm4mlperf-inference"
export CM_GIT_REPO_PATCH="no"
export CM_GIT_REPO_RECURSE_SUBMODULES=" --recurse-submodules"
export CM_GIT_REPO_URL="https://github.com/gateoverflow/cm4mlperf-inference"
export CM_MLPERF_INFERENCE_SUBMISSION_DIR="/home/cmuser/scc_gh_action_submissions"
export CM_MLPERF_RESULTS_GIT_REPO_URL="https://github.com/gateoverflow/cm4mlperf-inference"
export CM_MLPERF_RESULTS_REPO_COMMIT_MESSAGE="Results from self hosted Github actions - NVIDIARTX4090"
export CM_PYTHON_BIN="python3"
export CM_PYTHON_BIN_PATH="/home/cmuser/venv/cm/bin"
export CM_PYTHON_BIN_WITH_PATH="/home/cmuser/venv/cm/bin/python3"
export CM_PYTHON_CACHE_TAGS="version-3.10.12,non-virtual"
export CM_PYTHON_MAJOR_VERSION="3"
export CM_PYTHON_MINOR_VERSION="10"
export CM_PYTHON_PATCH_VERSION="12"
export CM_PYTHON_VERSION="3.10.12"
export CM_QUIET="yes"
export CM_RSYNC_VERSION="rsync  version 3.2.7"
export CM_TMP_CURRENT_PATH="/home/cmuser/scc_gh_action_submissions"
export CM_TMP_CURRENT_SCRIPT_PATH="/home/cmuser/CM/repos/gateoverflow@cm4mlops/script/push-mlperf-inference-results-to-github"
export CM_TMP_CURRENT_SCRIPT_REPO_PATH="/home/cmuser/CM/repos/gateoverflow@cm4mlops"
export CM_TMP_CURRENT_SCRIPT_REPO_PATH_WITH_PREFIX="/home/cmuser/CM/repos/gateoverflow@cm4mlops"
export CM_TMP_CURRENT_SCRIPT_WORK_PATH="/home/cmuser/scc_gh_action_submissions"
export CM_TMP_PIP_VERSION_STRING=""


. "/home/cmuser/CM/repos/gateoverflow@cm4mlops/script/push-mlperf-inference-results-to-github/run.sh"
